on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: paper

jobs:
  paper:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Render
        run: |
          rmarkdown::render("writeups/paper.Rmd", output_format =  "html_document")
        shell: Rscript {0}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: paper
          path: writeups
          if-no-files-found: error
